### ISSUE TITLE
Name Game elements not aligned.

### ISSUE THREAD

**Issue by sumeetjain** [omahacodeschool/bk-omawho#126]
See discrepancy of margins for image and text.

![screen shot 2014-04-27 at 11 09 25 pm](https://cloud.githubusercontent.com/assets/29388/2813507/f8b419aa-ce8a-11e3-929a-d87b960a6317.png)

**Comment by BLNorris** [comment]
This has been fixed on master and the staging site. has not been deployed to omawho.com yet.
