### ISSUE TITLE
Quizzes

### ISSUE THREAD

**Issue by kittee** [omahacodeschool/bk-omawho#19]
- One picture at a time
- Guess names
- Multiple choice for job

**Comment by kittee** [comment]
Mock-up references:
![Quiz before](https://cloud.githubusercontent.com/assets/1256165/2771909/84ae2fca-ca73-11e3-8f94-ecff2e9519b5.jpg)

![Quiz after](https://cloud.githubusercontent.com/assets/1256165/2771911/8c65875e-ca73-11e3-8160-3aeeb9cc4eb2.jpg)

**Comment by danwells** [comment]
This branch has been merged into master.
