### ISSUE TITLE
Overall static design

### ISSUE THREAD

**Issue by kittee** [omahacodeschool/bk-omawho#4]
User
- [x] Index (root)
- [x] New
- [x] Show
- [x] Edit

Events
- [x] Index

Login
- [x] New

Site Pages
- [x] About

Quiz
- [x] Quiz page

**Comment by kaitlynhova** [comment]
Hey! I'd like to help out with this -- What were your thoughts, Jay and Michael? : )

**Comment by kaitlynhova** [comment]
Hey! So this sort of a thing I was thinking of for the landing page. I really want something that takes all of the data that everyone is giving (for example, their profile photos) and having it "put a face to" Omaha's Creative community as soon as the visitors enter the site. What do you think of that kind of a thing?  I was thinking that it would be a "random profile image" generator that would grab users images with by random ids. 

![landingpageidea](https://cloud.githubusercontent.com/assets/5474124/2759682/56aad552-c9a5-11e3-907f-d6596e2ba2ea.png)

**Comment by kittee** [comment]
This is a cool design! Although one of my concerns is that it looks like with this design, it will take an extra click to go to another page to start looking people up, whereas the current Omawho, you can start clicking on people right away from the homepage. Maybe instead of "Omawho" and the tagline in the dead center of the page, we keep it at the top in the header, but the pictures taking up the page like this definitely helps emphasize that the focus is the faces of Omaha.

**Comment by kittee** [comment]
I'm just going to add what Michael and Jay have come up with so we can have these two mock-ups on the page together to compare more easily:

![Omawho mock up](https://s3.amazonaws.com/uploads.hipchat.com/83279/626046/z7m3LAIiZ0ZsDTJ/Omawho.jpg)

I like their header and navigation bar area, and I like how your (Kait's) draft adds more focus to the faces, and the overall feel is classier.

**Comment by kaitlynhova** [comment]
What if we maybe did a full page of random people for the front page like this? 
![generaliconlayout](https://cloud.githubusercontent.com/assets/5474124/2759902/bcdb7454-c9a9-11e3-8c9b-e40cc8a6f4f0.png)

**Comment by kittee** [comment]
Yeah, this takes what I liked from both designs. :)

I'm not so sure about the name and tagline being vertically centered because it obscures their faces. I think it might look better bottom-aligned, and by default the images could be opacity 0.9, on hover fade to 1 and have the name/tagline appear.

Also if we're relying entirely on the hover effect to make the name/tagline appear, that will make the user's mobile experience more difficult. Maybe just for mobile, the name/tagline can already be there.

Just so you know, color schemes and fonts are still really up in the air, we probably won't finalize that until tomorrow. So this turquoise isn't necessarily what's staying forever.

**Comment by kaitlynhova** [comment]
Sweet -- I can make the hover effects work in sort of a compromise on mobile. Maybe making the images have the bottom aligned title? Maybe we can use the random image selector for something cool on the about page?

**Comment by kittee** [comment]
Yeah, we haven't given much thought to the layout of the About page. That's still up in the air, too, if you have ideas for it.

**Comment by kaitlynhova** [comment]
Just throwing this idea in the pot as well for the front page! One of the things that I thought the current Omahwho website could have done better was to make it look like it was more than just a bunch of user data. Just trying to figure out how to dress up all the data so that it seems more exclusive and noteworthy than it is right now (which looks like a bunch of creative people just signed up to be on this website). 
![frontpageidea2](https://cloud.githubusercontent.com/assets/5474124/2760029/f53bb83e-c9ab-11e3-93d2-339531e0f8da.png)

**Comment by jayshaw** [comment]
Hey guys! Here are a few possible logo treatments. Since we had a few layouts with slab serif and serif fonts already. I played with script and rounded serif with bright colors to give it a playful feel.
![omawho mockups](https://cloud.githubusercontent.com/assets/5830738/2761322/4430bbda-c9d2-11e3-9831-7c3bec8d53e0.jpg)

---

![omawho mockups2](https://cloud.githubusercontent.com/assets/5830738/2761324/44324cb6-c9d2-11e3-9ef7-87314b669288.jpg)

---

![omawho mockups3](https://cloud.githubusercontent.com/assets/5830738/2761323/4430f578-c9d2-11e3-8fd7-6923e48cbaf2.jpg)

Lots to talk about tomorrow. Kate we hope your feeling better.

**Comment by kittee** [comment]
Jay, my favorite of your mock-ups is the first one. I really like that logo and the integration of the question mark, and I like how the navigation bar overlays on the banner with just a little bit of transparency. We are missing important things from Michael's mock-up though (the category filtering and search bar), so instead of the tagline on that bottom section of the banner, perhaps the tagline can go under the logo and put the category filtering and search bar there instead.

One other thing is that I think we should keep the banner shorter than these drafts so the faces are still the main emphasis. Probably closer to the height Michael is using, so somewhere in the range of 150-200 px.

And yeah, there is a lot to talk about tomorrow (or rather, later today because I'm up past midnight for some reason). You guys have a lot of great ideas! And I think there are good things from all of these that can be pulled into one cohesive design.

**Comment by kittee** [comment]
Here's my skyline illustration that I would really like to use for the banner if you guys like it, too. I tried to keep the colors muted so it wouldn't be difficult to overlay the logo on it, but we can also use Jay's subtle drop shadow to make it legible.

![Omaha skyline](https://cloud.githubusercontent.com/assets/6446911/2761808/311ca31e-c9e2-11e3-80da-78555daa7a73.jpg)

**Comment by htmlmt** [comment]
Really great work, everyone! I love the skyline, the logo and Kait's designs.

Here's what I have so far for a homepage design (minus footer content) that begins to bring everything together:

![omawho homepage](https://cloud.githubusercontent.com/assets/1256165/2764655/7d643bd4-ca18-11e3-9f94-d2351665fc62.jpg)

**Comment by kittee** [comment]
Larger buildings image:
![Omaha skyline large](https://cloud.githubusercontent.com/assets/6446911/2769018/2dd11a2c-ca4c-11e3-871f-0a523643ad08.jpg)

**Comment by htmlmt** [comment]
# The Big List of All Mockups

## Desktop

### Homepage

![omawhohomepage](https://cloud.githubusercontent.com/assets/1256165/2771888/43074b42-ca73-11e3-9177-edb7056dad50.jpg)

### Homepage with Categories

![omawhohomepagecategories](https://cloud.githubusercontent.com/assets/1256165/2771895/5a094d22-ca73-11e3-91c3-a5e68d6c328f.jpg)

### Login Page

![omawhosession](https://cloud.githubusercontent.com/assets/1256165/2772008/44b3be2e-ca75-11e3-9083-e1100e4e3d03.jpg)

### Sign Up Page

![omawhousernew](https://cloud.githubusercontent.com/assets/1256165/2772017/65f8b396-ca75-11e3-86f4-11daaec5a1d4.jpg)

### Profile Page

![omawhoprofilepage](https://cloud.githubusercontent.com/assets/1256165/2771975/a5569982-ca74-11e3-8d63-6b3564cabe76.jpg)

### Events Page

![omawhoevents](https://cloud.githubusercontent.com/assets/1256165/2771901/74bcaa2e-ca73-11e3-8ee3-0eb6f1215fb9.jpg)

### Name Game

![omawhonamegame](https://cloud.githubusercontent.com/assets/1256165/2771909/84ae2fca-ca73-11e3-8f94-ecff2e9519b5.jpg)

### Name Game Results

![omawhonamegameresult](https://cloud.githubusercontent.com/assets/1256165/2771911/8c65875e-ca73-11e3-8160-3aeeb9cc4eb2.jpg)

### About Page

![omawhoabout](https://cloud.githubusercontent.com/assets/1256165/2771915/9c819984-ca73-11e3-8da1-b8ead49702e8.jpg)

## Mobile

### Homepage

![omawhomobilehomepage](https://cloud.githubusercontent.com/assets/1256165/2771923/c3949fee-ca73-11e3-9bf9-8bd8ddc766f2.jpg)

### Profile Page

no mockup

### Events Page

no mockup

### Name Game

no mockup

### Name Game Results

no mockup

### About Page

no mockup
