### ISSUE TITLE
Font choices

### ISSUE THREAD

**Issue by kittee** [omahacodeschool/bk-omawho#5]

**Comment by kaitlynhova** [comment]
Which font choices have you guys thought of? I have typekit -- I'll start posting a bunch of those ideas in a bit ~

**Comment by kaitlynhova** [comment]
Do we want to stick with a similar font or completely mix it up?

**Comment by kittee** [comment]
The fonts are up in the air right now. Jay is coming up with ideas; you can throw in ideas for type, too.
